### PR TITLE
Ruby 1.9 compatibility done!

### PR DESCRIPTION
**Pull request by robsonmwoc**
Hello Bryan,

there is a good time since our last contact when I asked to you about the RailRoad development timeline. And now I'm sending my pull request for ruby 1.9.x compatibility, and Rails 3 as well.

Feel free to merge the commits or simple check the differences.

Bye,
Robson Mendonça.

### CODE REVIEW

**Comment by bryanlarsen** [comment]
Have you tested your pull request for Rails2.3 compatibility?   At a quick glance, the May31 commits look OK, but the June 2 one might be problematic.

**Comment by robsonmwoc** [comment]
Ohh, my bad.

I will check it and build a new patch.

Sorry.

## 

Robson Mendona
Desenvolvedor RubyOnRails - Fande.com.br
http://myweboncreate.com

**Comment by robsonmwoc** [comment]
Actually, I was checking here, and the patch works with Rails 2.3.x and Ruby 1.8 too. Did you have any problems with this patch?

**Comment by bryanlarsen** [comment]
Nope, it was just a visual inspection.

On Fri, Jun 17, 2011 at 11:58 AM, robsonmwoc
reply@reply.github.com
wrote:

**Comment by TauPan** [comment]
Since hoe didn't work right out of the box, I tried building the gem with gem build and noticed an error in the gemspec.

https://github.com/TauPan/railroad/commit/3372b60570552f1445bba3bfd2a2a691eb2fc7f5

**Pull request closed without merging**
